version: "2.2"

services:
    rabbitmq:
        image: rabbitmq:3.10.7-management-alpine
        environment:
            - RABBITMQ_DEFAULT_USER=${RABBITMQ_USER}
            - RABBITMQ_DEFAULT_PASS=${RABBITMQ_PASS}
        volumes:
            - rabbitmq-data:/var/lib/rabbitmq
        ports:
            - 5672:5672
            - 15672:15672

volumes:
  rabbitmq-data:
