// Code generated by mockery v2.14.0. DO NOT EDIT.

package cstx

import (
	errs "github.com/matrixbotio/rmqworker-lib/pkg/errs"
	mock "github.com/stretchr/testify/mock"

	structs "github.com/matrixbotio/rmqworker-lib/pkg/structs"
)

// mockHandler is an autogenerated mock type for the handler type
type mockHandler struct {
	mock.Mock
}

type mockHandler_Expecter struct {
	mock *mock.Mock
}

func (_m *mockHandler) EXPECT() *mockHandler_Expecter {
	return &mockHandler_Expecter{mock: &_m.Mock}
}

// PublishCSXTToExchange provides a mock function with given fields: task, cstx
func (_m *mockHandler) PublishCSXTToExchange(task structs.PublishToExchangeTask, cstx CrossServiceTransaction) errs.APIError {
	ret := _m.Called(task, cstx)

	var r0 errs.APIError
	if rf, ok := ret.Get(0).(func(structs.PublishToExchangeTask, CrossServiceTransaction) errs.APIError); ok {
		r0 = rf(task, cstx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(errs.APIError)
		}
	}

	return r0
}

// mockHandler_PublishCSXTToExchange_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PublishCSXTToExchange'
type mockHandler_PublishCSXTToExchange_Call struct {
	*mock.Call
}

// PublishCSXTToExchange is a helper method to define mock.On call
//  - task structs.PublishToExchangeTask
//  - cstx CrossServiceTransaction
func (_e *mockHandler_Expecter) PublishCSXTToExchange(task interface{}, cstx interface{}) *mockHandler_PublishCSXTToExchange_Call {
	return &mockHandler_PublishCSXTToExchange_Call{Call: _e.mock.On("PublishCSXTToExchange", task, cstx)}
}

func (_c *mockHandler_PublishCSXTToExchange_Call) Run(run func(task structs.PublishToExchangeTask, cstx CrossServiceTransaction)) *mockHandler_PublishCSXTToExchange_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(structs.PublishToExchangeTask), args[1].(CrossServiceTransaction))
	})
	return _c
}

func (_c *mockHandler_PublishCSXTToExchange_Call) Return(_a0 errs.APIError) *mockHandler_PublishCSXTToExchange_Call {
	_c.Call.Return(_a0)
	return _c
}

// PublishCSXTToQueue provides a mock function with given fields: task, cstx
func (_m *mockHandler) PublishCSXTToQueue(task structs.RMQPublishRequestTask, cstx CrossServiceTransaction) errs.APIError {
	ret := _m.Called(task, cstx)

	var r0 errs.APIError
	if rf, ok := ret.Get(0).(func(structs.RMQPublishRequestTask, CrossServiceTransaction) errs.APIError); ok {
		r0 = rf(task, cstx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(errs.APIError)
		}
	}

	return r0
}

// mockHandler_PublishCSXTToQueue_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PublishCSXTToQueue'
type mockHandler_PublishCSXTToQueue_Call struct {
	*mock.Call
}

// PublishCSXTToQueue is a helper method to define mock.On call
//  - task structs.RMQPublishRequestTask
//  - cstx CrossServiceTransaction
func (_e *mockHandler_Expecter) PublishCSXTToQueue(task interface{}, cstx interface{}) *mockHandler_PublishCSXTToQueue_Call {
	return &mockHandler_PublishCSXTToQueue_Call{Call: _e.mock.On("PublishCSXTToQueue", task, cstx)}
}

func (_c *mockHandler_PublishCSXTToQueue_Call) Run(run func(task structs.RMQPublishRequestTask, cstx CrossServiceTransaction)) *mockHandler_PublishCSXTToQueue_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(structs.RMQPublishRequestTask), args[1].(CrossServiceTransaction))
	})
	return _c
}

func (_c *mockHandler_PublishCSXTToQueue_Call) Return(_a0 errs.APIError) *mockHandler_PublishCSXTToQueue_Call {
	_c.Call.Return(_a0)
	return _c
}

// PublishToExchange provides a mock function with given fields: task, additionalHeaders
func (_m *mockHandler) PublishToExchange(task structs.PublishToExchangeTask, additionalHeaders ...structs.RMQHeader) errs.APIError {
	_va := make([]interface{}, len(additionalHeaders))
	for _i := range additionalHeaders {
		_va[_i] = additionalHeaders[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, task)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 errs.APIError
	if rf, ok := ret.Get(0).(func(structs.PublishToExchangeTask, ...structs.RMQHeader) errs.APIError); ok {
		r0 = rf(task, additionalHeaders...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(errs.APIError)
		}
	}

	return r0
}

// mockHandler_PublishToExchange_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PublishToExchange'
type mockHandler_PublishToExchange_Call struct {
	*mock.Call
}

// PublishToExchange is a helper method to define mock.On call
//  - task structs.PublishToExchangeTask
//  - additionalHeaders ...structs.RMQHeader
func (_e *mockHandler_Expecter) PublishToExchange(task interface{}, additionalHeaders ...interface{}) *mockHandler_PublishToExchange_Call {
	return &mockHandler_PublishToExchange_Call{Call: _e.mock.On("PublishToExchange",
		append([]interface{}{task}, additionalHeaders...)...)}
}

func (_c *mockHandler_PublishToExchange_Call) Run(run func(task structs.PublishToExchangeTask, additionalHeaders ...structs.RMQHeader)) *mockHandler_PublishToExchange_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]structs.RMQHeader, len(args)-1)
		for i, a := range args[1:] {
			if a != nil {
				variadicArgs[i] = a.(structs.RMQHeader)
			}
		}
		run(args[0].(structs.PublishToExchangeTask), variadicArgs...)
	})
	return _c
}

func (_c *mockHandler_PublishToExchange_Call) Return(_a0 errs.APIError) *mockHandler_PublishToExchange_Call {
	_c.Call.Return(_a0)
	return _c
}

type mockConstructorTestingTnewMockHandler interface {
	mock.TestingT
	Cleanup(func())
}

// newMockHandler creates a new instance of mockHandler. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func newMockHandler(t mockConstructorTestingTnewMockHandler) *mockHandler {
	mock := &mockHandler{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
